### PR TITLE
Add public networking.

### PR DESCRIPTION
**Pull request by jmcarp**
So that instances can be publicly accessible.

@LinuxBozo: could you review?
cc @ccostino

### CODE REVIEW

**Review by LinuxBozo — APPROVED** [review]
Looks good, but you probably want to re-visit your security group for proper ingress rules.

**Review by LinuxBozo — APPROVED** [review]

**Comment by jmcarp** [comment]
> you probably want to re-visit your security group for proper ingress rules.

Definitely, but I'm going to leave this for @ccostino, since I don't know exactly how FEC accesses the databases.

**Comment by ccostino** [comment]
Now that we're done with PI planning we can get back to this stuff.  I'll review with @LindsayYoung and we'll adjust as necessary.  Thanks!

**Review by ccostino — APPROVED** [review]
Thanks, @jmcarp and @LinuxBozo!  @LindsayYoung are comfortable with this for now and will make adjustments in the future.

**Pull request merged**
